spring.application.name=touralert
server.port=8081

# Fix the H2 database name so it stays constant
spring.datasource.url=jdbc:h2:mem:touralertdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Turn on the Web Browser Interface for our database
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Show our database activities in the terminal
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
# Google Maps API key (leave empty for development; set in production)
maps.api.key=